---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gpu-devplatforms-io-v1alpha1-leftovernodepool
  failurePolicy: Fail
  name: mleftovernodepool-v1alpha1.kb.io
  rules:
  - apiGroups:
    - gpu.devplatforms.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - leftovernodepools
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gpu-devplatforms-io-v1alpha1-leftovernodepool
  failurePolicy: Fail
  name: vleftovernodepool-v1alpha1.kb.io
  rules:
  - apiGroups:
    - gpu.devplatforms.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - leftovernodepools
  sideEffects: None
