---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gpu.devplatforms.io
  resources:
  - leftovernodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gpu.devplatforms.io
  resources:
  - leftovernodepools/finalizers
  verbs:
  - update
- apiGroups:
  - gpu.devplatforms.io
  resources:
  - leftovernodepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - karpenter.k8s.aws
  resources:
  - ec2nodeclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - karpenter.sh
  resources:
  - nodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
