apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Build on top of the default stack (CRDs, RBAC, manager, webhooks, etc.)
resources:
  - ../../default

patches:
  - path: serviceaccount_irsa_patch.yaml
  - path: manager_env_patch.yaml
