apiVersion: v1
kind: ServiceAccount
metadata:
  name: leftover-controller-manager
  namespace: leftover-system
  annotations:
    # TODO: Set your IRSA role ARN here (account, role name)
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<IRSA_ROLE_NAME>
